### ISSUE TITLE
Translation of "Read More"

### ISSUE THREAD

**Issue by pagliaso** [t3brightside/pagelist#1]
Hello,

I am using your very good extension on a typo3 test site.

After last update, I can't translate the tag "Read More".

I think I use to be able to translate this through Translate extension, but now in there can not see any file to translate.

Many thanks and kind regards from Spain,

Alb

**Comment by t3brightside** [comment]
Hey thanks,

right now the language files are still in XML format and can be translated using custom language file. Will be changed to XLF in next version. It then should be editable in translation extensions.

T

**Comment by pagliaso** [comment]
Many thanks for your prompt reply.

I have been able to get the translation to Spanish that I wanter with your help and XML file.

Thanks and kind regards from Spain,

Alb
