### ISSUE TITLE
Issue with Category Filter?

### ISSUE THREAD

**Issue by pagliaso** [t3brightside/pagelist#12]
Hello,

I recently updated to version 2.3.1 of your very good extension.

I am having an issue that if I do not reconfigure the pages where I had the extension, I get an error:

ERROR: Content Element with uid "797" and type "pagelist_category" has no rendering definition!

But, when I open each content element and reconfigure it, and select to show subpages, and filter by category, another error appears (Oops, an error occurred! Code: 201911122359114e6b7ade
), and the content elements are not shown.

Everything works properly if I select the pages that must appear in Pagelist, instead of filter by Category, or if I do not filter by any Category at all.

I don't know what I am doing wrong.

Many thanks and kind regards from Spain,

Alb

**Comment by t3brightside** [comment]
Hey!

Content type "pagelist_category" got removed in latest development. Sorry forgot to mention it, and it's a breaking change. Content element "Pagelist: subpages" now has category filter. This content type most likely get's some improvements still, but should be able to replace the "pagelist_category" content type.

Hopefully it works out this way for you. 

Thanks for the feedback!

**Comment by pagliaso** [comment]
Hello!

Many thanks for getting back to me so quickly.

I already changed the content type, but I am not able to get it working when I filter by category.

> Oops, an error occurred! Code: 2019111308582668c84214

If I do not filter by category everything is fine and working as it should.

Many thanks and kind regards,

Alb

**Comment by t3brightside** [comment]
@pagliaso  oh, I see, I got it wrong at first. Would be helpful if you can copy the actual error message from the logs. Thanks.

**Comment by t3brightside** [comment]
@pagliaso - I believe it should be fine in latest version 2.3.3 now. Sort order didn't play well with categories.

**Comment by pagliaso** [comment]
Hello @t3brightside ,

Many thanks for your message.

Uhm, I have updated to last version, modified content element, saved it, but it is not working yet for me...

I am not able to find an error on the logs, just the Oops, an error occurred! Code: 20191129150333e5d5a7e5 on the frontend?!

Many thanks and kind regards,

**Comment by t3brightside** [comment]
> Uhm, I have updated to last version, modified content element, saved it, but it is not working yet for me...
> 
> I am not able to find an error on the logs, just the Oops, an error occurred! Code: 20191129150333e5d5a7e5 on the frontend?!
> 
> Many thanks and kind regards,

You may want to try saving the content element with different sort order and then change it back to default, then it will be overwritten in the database.

Error log is in the var/log/ folder.

Cheers!
