### ISSUE TITLE
Pages hidden in menu don't appear in pagelist: selected

### ISSUE THREAD

**Issue by HenryAveMedi** [t3brightside/pagelist#13]
Pagelist of subpages behaves properly when page is hidden in menu but active for pagelist.
in pagelist: selected, that's not the case

**Comment by t3brightside** [comment]
Hey, thanks! Indeed, seems to be problematic. 
Adding this to TS setup should help. Will be added to next release.
tt_content.pagelist_selected.dataProcessing.10.includeNotInMenu = 1

**Comment by HenryAveMedi** [comment]
> Hey, thanks! Indeed, seems to be problematic.
> Adding this to TS setup should help. Will be added to next release.
> tt_content.pagelist_selected.dataProcessing.10.includeNotInMenu = 1

excellent, thnk you very much! especially for the fast response :D

**Comment by HenryAveMedi** [comment]
BTW: dunno if reporting the following makes sense, but the ext also renders the menu dividers (maybe even recycler, and other stuff, havent tested)……  i did my own templates aynways and turn off rendering for pagetypes < 190 as well
`{page.data.doktype} < 136 || ({page.data.doktype} > 138 && {page.data.doktype} < 190)`
but as i said, ppl might want this behavior, so, wont post an issue on this, but good to keep in mind

**Comment by t3brightside** [comment]
Not a bad idea maybe to add it as a template constant in future. Thanks for the idea!

**Comment by t3brightside** [comment]
Technical pages are now excluded from the page list and can be adjusted using a constant.
