### ISSUE TITLE
Sorting of Pagelist: category

### ISSUE THREAD

**Issue by 7L3HN** [t3brightside/pagelist#14]
Hi,

how can i sort the entries of pagelist: category module?

Is there any value that i can change with typoscript?

Thx a lot

**Comment by t3brightside** [comment]
Hey,

there is no more category module in later versions but category filter and should be ok with sorting.

**Comment by 7L3HN** [comment]
i have version 1.1.0 with typo3 8 - so i can't sort that list?

**Comment by t3brightside** [comment]
Nop, sorry, feature is not there really on earlier versions.
