### ISSUE TITLE
Rendering of lists is slow

### ISSUE THREAD

**Issue by vmans** [t3brightside/pagelist#18]
Your extension fills in a few blanks, thanks for your work.

But it seems that the rendering of lists is slow and not cached. Are caching methods implemented?

(perhaps compare to the extension Menu, https://extensions.typo3.org/extension/menus)

**Comment by t3brightside** [comment]
It's all based on TypoScript and Fluid. Never had caching issues, rendering is slow only if first time rendering the images.

**Comment by vmans** [comment]
I don'tuse images. But changing an sorting order, for instance, inflicts a new caching and takes many seconds.

**Comment by t3brightside** [comment]
Naturally cache has to be rebuilt if changing the setting in back end.
