### ISSUE TITLE
Appearance fields of the content element are dismissed

### ISSUE THREAD

**Issue by vmans** [t3brightside/pagelist#19]
In the tab Appearance of the content element, many fields are gone.

I now see only Lay-out, Frame, and the Links palette.

**Comment by t3brightside** [comment]
Never had issues with that, could be conflicting extensions or some setup problem/conflict.

**Comment by vmans** [comment]
Yeah, it conflicts with t3sbootstrap. I can fix the conflict but may be it should be fixed out of the box since that extension is used a lot.

**Comment by t3brightside** [comment]
t3bootstrap doesn't define appearance fields for custom extensions and content elements. You have to extend t3bootstrap yourself for that reason. It's not really a conflict with the extension.
