### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by hagerp** [t3brightside/pagelist#2]
#1283790586: There is no entry in the $TCA array for the table "tx_personnel_domain_model_person". This means that the function enableFields() is called with an invalid table name as argument.

**Comment by hagerp** [comment]
Does the Extension only work with the personnel extension?

**Comment by t3brightside** [comment]
It's a bug. Thanks for reporting, it should work without the personnel extension. Fix is coming up in couple days.

**Comment by t3brightside** [comment]
@hagerp feel free to check out the latest master, there's now conditions added to check if the personnel ext is installed or not. Bug fix release is coming up soon.
