### ISSUE TITLE
Double loading of the two content types

### ISSUE THREAD

**Issue by vmans** [t3brightside/pagelist#20]
As you can see in the images.

![image](https://user-images.githubusercontent.com/25581914/111074160-ff42ad80-84e1-11eb-8f74-7519cdb30928.png)

![image](https://user-images.githubusercontent.com/25581914/111074264-7d06b900-84e2-11eb-86ac-ded5e27d1d4c.png)

**Comment by t3brightside** [comment]
Can not recreate that issue with latest version...For testing I recommend to start with a clean install and default language.

**Comment by t3brightside** [comment]
Please open the issue again, if it's present with a clean TYPO3 install and or if there's a conflict with another extension.
