### ISSUE TITLE
Extension key in composer.json for v10 compatible extension

### ISSUE THREAD

**Issue by EvilBMP** [t3brightside/pagelist#22]
Could you please add the "extra" part in the composer.json of the v2.x version of the extension as well and release a v2.5.1? That would be very nice, as it is the only extension in our v10 projects, where the composer install is still complaining about that fact. Thanks allot.

```
        "extra": {
		"typo3/cms": {
			"extension-key": "pagelist"
		}
	}
```

**Comment by t3brightside** [comment]
Thanks for the note. Older versions won't be updated no more.

**Comment by EvilBMP** [comment]
Why is v10 compatible = old? It is still an active TYPO3 LTS version and not an ELTS. But ok...
