### ISSUE TITLE
View with three columns for wide screens

### ISSUE THREAD

**Issue by olli1991** [t3brightside/pagelist#23]
Hello,
is it correct, that a view with three colums is not available at version 3.6.0 and 3.7.0?
I cannot find the following constants:
- pagelist.cardsBreakTwo
- pagelist.cardsBreakOne

Have you removed this feature or is this a bug?

Thanks,
Oliver

**Comment by t3brightside** [comment]
Hey, yes it's removed.
It's in ChangeLog at v3.6.0 - [TASK] Remove JS for template breakpoints, use CSS grid instead

Should be doable with CSS flex or grid these days.
