### ISSUE TITLE
Sorting 

### ISSUE THREAD

**Issue by wini2** [t3brightside/pagelist#3]
hi,

thanks for that useful extension. 

when using Pagelist:subpages (version 2.1.2/TYPO3 9.5.2) with the setting Sort by: Page tree (default) the output is not sorted like in regular menus/sitemaps. it seems that the page id is the sorting citeria. how/where could i adjust this?

ps:  is it possible to collect regular content elements (text, text/media)? if yes, would you please give me a hint.

**Comment by t3brightside** [comment]
Hey, thanks for pointing out. It's fixed now in the latest master.

Showing content elements is not included in this extension and no plans to add this feature now.

**Comment by wini2** [comment]
hi, thanks for fixing it so fast - the sorting works like expected. 
a small issue after updating tt_content.php: the selected entry of the flexform field Sort By is [INVALID VALUE ("0")].

**Comment by t3brightside** [comment]
Just need to be saved again the content element or patch update the database. Sorry, can't provide update script to that now.
