### ISSUE TITLE
Using Page Resource Images instead of Creating Listimages 

### ISSUE THREAD

**Issue by hogiro** [t3brightside/pagelist#4]
Hello,

thanks for the useful extension.

I just wanna do a suggestion: instead of creating completely new fields for listimages you could easily use the existing fields for page resource images. 

For that you just need to change the cards as following:
```
<f:if condition="{page.listimages.0}">
          <f:then>
            <img src="<f:uri.image image="{page.listimages.0}" treatIdAsReference="1" width="900c" height="600c" />" alt="{f:if(condition:'{page.listimages.0.alternative}', then:'{page.listimages.0.alternative}', else:'{page.data.title}')}" class="image" />
          </f:then>
```

with:
```
<f:if condition="{page.files.0}">
          <f:then>
            <img src="<f:uri.image image="{page.files.0}" treatIdAsReference="1" width="900c" height="600c" />" alt="{f:if(condition:'{page.listimages.0.alternative}', then:'{page.listimages.0.alternative}', else:'{page.data.title}')}" class="image" />
          </f:then>
```

Of course you can improve the checking and listing the existing images btw my fast dirty change.

**Comment by t3brightside** [comment]
Hey, thanks for the feedback! No plans to change that feature. Resource image can still be used for different purposes and it's as easy as you show to change it for personal needs or as a fallback for the projects where's the image is already present on resources field.
