### ISSUE TITLE
Pagelist:category start item does not work

### ISSUE THREAD

**Issue by fanpalm** [t3brightside/pagelist#5]
Hi,
very flexible extension, thank you. 
Start item and items shown works for subpages fine, but not for categories.
Sorting options as for he subpages would be helpful as well.

I can imagine it's not that simple to have that working, as you would need to use queries like for the subpages.

**Comment by t3brightside** [comment]
Hey, thanks for the feedback. For now indeed Category function is very basic. It most probably sees a bit more care once it comes an actual need in a project. Hard to find time otherwise.

**Comment by t3brightside** [comment]
Even thou, start item and items shown should work in latest master now for the cat view, sorting needs different approach still.
