### ISSUE TITLE
ext:pagelist without ext:fluid_styled_content 

### ISSUE THREAD

**Issue by typo3ua** [t3brightside/pagelist#6]
How to be when I am do not use the `ext:fluid_styled_content`, and I am use the `ext:bootstrap_package` (or I can use my own rendering of a content elements)?

Is there a any way using the `ext:pagelist` without `ext:fluid_styled_conten`t? 

How to avoid the `ext:fluid_styled_content` in the `ext:pagelist` when I need the `ext:bootstrap_package`?

**Comment by t3brightside** [comment]
Hey, it should be fairly easy to configure pagelist to work without ext:fluid_styled_content. Just have a look at the main TypoScript configuration.
