### ISSUE TITLE
pagelist does not show images from subsub pages

### ISSUE THREAD

**Issue by asche76** [t3brightside/pagelist#7]
pagelist does not show images from subsub pages (typo3 9)
![image](https://user-images.githubusercontent.com/47745128/52951490-39343a80-3382-11e9-91ac-22830460e4c6.png)
![image](https://user-images.githubusercontent.com/47745128/52951507-42250c00-3382-11e9-96e8-2c19d58fa934.png)

**Comment by t3brightside** [comment]
Hey, sorry but this information is not sufficient telling if it's a bug, a problem with a setup, content editing or something else.

**Comment by asche76** [comment]
hi...
hm, ok i've tried all i can, all variantions in settings, abstracts from
subsub pages work out of the box, then why not the image from the same page
properties? there are only pagelist dummy pngs instead of the image from
the page properties resources.
here the structure:
- root page
-- first level page (ext placed)
--- sub page (images from here shown in ext, abstracts from here shown in
ext)
---- subsub page (no images shown from here in ext plugin, only dummy png,
abstracts also shown from here in ext)


thx for the answer

**Comment by t3brightside** [comment]
So...
1. Content type is: "Pagelist: selected"?
2. Selected pages are: sub page, subsub page?
3. Image is added to the: subsub page field "Pagelist image"?

Content type "Pagelist: subpages" is not meant for multilevel structure but only for the first sub level.

**Comment by asche76** [comment]
1. yes
2. yes
3. nice, is the pagelist image field new? it works now for subsub pages
so far i used files media relation, it worked for subpages....
however many many thanks - best regards

**Comment by asche76** [comment]
![image](https://user-images.githubusercontent.com/47745128/53327254-b7935e00-38e7-11e9-811b-691ab696beb9.png)
