### ISSUE TITLE
respect language modes

### ISSUE THREAD

**Issue by Hobokens** [t3brightside/pagelist#8]
Hi,
thanks a lot for your useful extension. I use it on a bilingual website (German/English).
I encountered a problem with "subpages from".  If not all German pages are translated, they are still listed withPagelist as subpages on the English page. I would have expected only the translated pages to be listed.
Best regards
Hobokens

TYPO3 9.5.8, Pagelist 2.2.1

**Comment by t3brightside** [comment]
Indeed it's a problem now. TYPO3\CMS\Frontend\DataProcessing\DatabaseQueryProcessor seems not to respect languages in that context. MenuProcessor on the other hand does, maybe it's possible for you to use MenuProcessor instead, changing it in TypoScript setup. Anyhow, looking for the solution as well...
More about it here: https://forge.typo3.org/issues/85934

**Comment by Hobokens** [comment]
Thanks for the confirmation and the advice. I will take a look as soon as possible,

**Comment by t3brightside** [comment]
@Hobokens one more option in 9.5 LTS is to set language "Fallback Type" in site configuration to "Free mode: Ignore translation and overlay concept, only show data from selected language". mode "Strict: Show only translated content, based on overlays" seems to be problematic. But it's problematic with Personnel author records then again.

**Comment by Hobokens** [comment]
@t3brightside, using "Free mode: Ignore translation and overlay concept, only show data from selected language" brings new problems. For example, in the extension events2 the categories are no longer translated.

**Comment by t3brightside** [comment]
Now in latest master, there's a rewritten WHERE clause, it should work in strict language mode now.

**Comment by Hobokens** [comment]
Thanks a lot for the improvement - the problem is solved for me.
