### ISSUE TITLE
no image shown

### ISSUE THREAD

**Issue by Hobokens** [t3brightside/pagelist#9]
Hi,

I have one more problem with pagelist v2.2.1 and TYPO3 9.5.8.

When I try to use a pagelist image from page ressources I get the following error:

`''Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Catchable Fatal Error: Object of class TYPO3\CMS\Core\Resource\FileReference could not be converted to string in /my/domain/rp-hosting/xxx/yyy/typo3cms/projekt1/typo3temp/var/cache/code/fluid_template/partial_Card_5a7e47228cc5aea3f106c381164de38ceb81d0af.php line 333 | TYPO3\CMS\Core\Error\Exception thrown in file /kunden/xxxxxxxxx/rp-hosting/xxx/yyy/typo3cms/typo3_src-9.5.8/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 124. Requested URL: https://www.my-domain.de/test/site/''`

Regards
Hobokens

**Comment by t3brightside** [comment]
Hey, thanks for sharing. Does the issue appear within the default template? Can't reproduce the issue by this description and can't guess what can it be.

**Comment by Hobokens** [comment]
I'm sorry. It's my fault. I had a misconfiguration within my own template. Now everything is fine.

Have a nice day!
Hobokens
